spring:
  datasource:
    username: root
    password: ymsyms
    url: jdbc:mysql://localhost:3306/task_view?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 1
    maxActive: 50
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
